// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef CARLA_ROS_SCENARIO_RUNNER_TYPES__MSG__CARLA_SCENARIO_RUNNER_STATUS_HPP_
#define CARLA_ROS_SCENARIO_RUNNER_TYPES__MSG__CARLA_SCENARIO_RUNNER_STATUS_HPP_

#include "carla_ros_scenario_runner_types/msg/detail/carla_scenario_runner_status__struct.hpp"
#include "carla_ros_scenario_runner_types/msg/detail/carla_scenario_runner_status__builder.hpp"
#include "carla_ros_scenario_runner_types/msg/detail/carla_scenario_runner_status__traits.hpp"
#include "carla_ros_scenario_runner_types/msg/detail/carla_scenario_runner_status__type_support.hpp"

#endif  // CARLA_ROS_SCENARIO_RUNNER_TYPES__MSG__CARLA_SCENARIO_RUNNER_STATUS_HPP_
